---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Check python3-psutil package status
      ansible.builtin.package:
        name: python3-psutil
        state: installed
      check_mode: true
      register: psutil_status

    - name: Show python3-psutil package status
      ansible.builtin.debug:
        msg: "{{ psutil_status }}"

    - name: Assert that python3-psutil package is installed
      ansible.builtin.assert:
        that: not psutil_status.changed
